<?php
/**
 * Created by PhpStorm.
 * User: wangye
 * Date: 2018/12/4
 * Time: 9:41 PM
 */

namespace App\Work\University;


use App\Work\BasesWork;

class BasesUniversity extends BasesWork
{
    public function downImg($cookie)
    {
        $imgCode = $this->getUnImg($cookie);
        return $imgCode;
    }

    public function getImgCode($base64_image)
    {
//        $imgCode="";
//        if (empty($imgBases)) {
        //这是老的方法 可能以后用的到
//            $path_parts = dirname(__FILE__);
//            $image_file = $path_parts . '/img/image.jpeg';
//            $image_data = fread(fopen($image_file, 'r'), filesize($image_file));
//            $base64_image = base64_encode($image_data);
//        }
        $base64_image_final = base64_encode($base64_image);
        try {
            $imgCode = $this->doImgCode($base64_image_final); // TODO: Change the autogenerated stub
            $code = $imgCode['words_result'][0]['words'];
            return $code;
        } catch (\Exception $exception) {
            $universModel = new \App\Models\University\Univers();
            $universModel->errorinfo = "errorinfo:" . json_encode($exception);
            $universModel->save();
        }
    }
}